[theme]
base = "light"
primaryColor = "#FF5252"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#334155"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
